### ISSUE TITLE
CI Failure because of Github API rate limitation

### ISSUE THREAD

**Issue by okozachenko1203** [vexxhost/magnum-cluster-api#128]
## conext
CI `functional` workflow is failing frequently at the step initiating capi because of gh api rate limit.
Here is the full error log.
```
+ clusterctl init --core cluster-api:v1.3.3 --bootstrap kubeadm:v1.3.3 --control-plane kubeadm:v1.3.3 --infrastructure openstack:v0.7.1
Fetching providers
Error: failed to get provider components for the "cluster-api:v1.3.3" provider: failed to read "core-components.yaml" from provider's repository "cluster-api": failed to get GitHub release v1.3.3: rate limit for github api has been reached. Please wait one hour or get a personal API token and assign it to the GITHUB_TOKEN environment variable
```

## solution
Need to use a personal token instead of CI job token. But not sure it means gh will charge us once the rate is over the quota instead of failing.

**Comment by okozachenko1203** [comment]
@mnaser what do you think?

**Comment by mnaser** [comment]
I think this issue has to do with the following two:

https://github.com/kubernetes-sigs/cluster-api/issues/2450
https://github.com/kubernetes-sigs/cluster-api/issues/3982

If we use the GitHub token, it'll be bound for a specific user which feels a little gross (since it might not be exposed to PRs for example)..

@okozachenko1203 since there is a cache layer that was introduced in the first bug issue, maybe we use the github cache for jobs to re-use that in jobs?

**Comment by okozachenko1203** [comment]
if we can fetch yaml files for the mgmt. cluster initialization using `clusterctl` cli(like `helm fetch`), then we can share those yaml files using gh action cache layer definitely.

**Comment by mnaser** [comment]
@okozachenko1203 i think this issue has almost disappeared since the new GOPROXY workaround seems to work just fine.. since we bumped to CAPI 1.4

I think we can close this since we haven't seen any issues for a while

**Comment by mnaser** [comment]
added GITHUB_TOKEN as well which will use the token provided by github actions and that has fixed it.
