### ISSUE TITLE
Cluster label fails to propagate when changing autoscaling

### ISSUE THREAD

**Issue by mnaser** [vexxhost/magnum-cluster-api#130]
When making a change to autoscaling configuration such as changing `{min,max}_node_count`, it seems that the annotations are not updated in the `machineDeployment` section of the cluster (and since we also manually update the machine deployments after because propagation doesn't happen yet, it doen't go into the actual machine deployment).

It also leaves the node group in a `UPDATE_IN_PROGRESS` state.

**Comment by okozachenko1203** [comment]
`*_node_count` can be updated by either `cluster_update` or `ng_update` actions. `cluster_update` action has not be implemented in the current mcapi driver. So i assume this error can be reproducible by `ng_update` action.

**Comment by okozachenko1203** [comment]
When we create a cluster autoscaling-enabled, `max_node_count` and `min_node_count` labels are not set in the nodegroup correctly. It is just considered as labels in ng.
```sh
ubuntu@mcapi-large:~$ o coe nodegroup show scale default-worker -f json
{
  "uuid": "c61acc4b-41f6-4ea9-834d-e0e04914a96b",
  "name": "default-worker",
  "cluster_id": "4e1910e1-35d1-4d99-913d-2ee5765156b2",
  "project_id": "2ffc6c32d8794e3289a34ca890c089f9",
  "docker_volume_size": null,
  "labels": {
    "auto_scaling_enabled": "true",
    "max_node_count": "2"
  },
  "labels_overridden": {},
  "labels_skipped": {},
  "labels_added": {},
  "flavor_id": "m1.medium",
  "image_id": "ef107f29-8f26-474e-8f5f-80d269c7d2cd",
  "node_addresses": [],
  "node_count": 1,
  "role": "worker",
  "max_node_count": null,
  "min_node_count": 0,
  "is_default": true,
  "stack_id": "kube-carvi",
  "status": "CREATE_COMPLETE",
  "status_reason": null
}
```

**Comment by okozachenko1203** [comment]
Seems this is an upstream issue? I can see that create_cluster handler just sets min_node_count for ng.

https://opendev.org/openstack/magnum/src/commit/b578bd8a78d890ad32aeb6066cc22ece165f54e2/magnum/conductor/handlers/cluster_conductor.py#L61-L63
https://opendev.org/openstack/magnum/src/commit/b578bd8a78d890ad32aeb6066cc22ece165f54e2/magnum/conductor/utils.py#L170-L196

**Comment by okozachenko1203** [comment]
btw, i was able to reproduce this issue. The reason is;
when the ng is updated, both the cluster status and ng status are updated as `UPDATE_IN_PROGRESS`. Then `driver.update_nodegroup()` is executed.
At the same time, the periodic task for sync cluster status will trigger the `driver.update_cluster_status()` because the cluster status is in `IN_PROGRESS`.

Before ng update handler is finished, the `driver.update_cluster_status()` (which runs `update_nodegroup_status` inside it) is finished. i.e. the cluster status and ng status are set as `UPDATE_COMPLETED` before the ng udpate handler sets the ng status as `IN_PROGRESS`.
Once the cluster status is `UPDATE_COMPLETED`, this cluster is skipped from the periodic task for sync cluster. i.e. `driver.update_cluster_status()` will never be executed even if the ng status is `UPDATE_IN_PROGRESS`.
