### ISSUE TITLE
Add default inter-cluster security group rules

### ISSUE THREAD

**Issue by adamhackl** [vexxhost/magnum-cluster-api#182]
A magnum cluster gets spun up with some default rules for the workers and cp nodes to communicate with each other. E.g. Kubelet API 10250 rule. Is there a way we can add additional ports at deployment with the same pattern? I have some ports that I need to add to each cluster for monitoring, such as 9100 for node-exporter and 10249 for kube-proxy ...

**Comment by mnaser** [comment]
This has been a reoccuring issue that is being brought up, however, there are some challanges in here:

- If the user would use the pre-existing security groups, it would work until there is a change in the cluster which would result in a reconcile and their changes would disappear, this is a no go.
- If the user would add a new security group to the VMs, that wouldn't work due to the fact that the autoscaler can add/remove and reconciles can make changes
- If we had a label called `allowed_ports` or something, it would not be super useful because of the limitation of the Magnum API not allowing you to change labels after the fact.. so that means if you ever want to make a change down the line.. not possibel

The only possible reasonable solution I can think of is that we create 2 extra security groups (perhaps one for control plane and one for workers) and then you can make changes to them with different rules.  Unfortunately, this is not great for users who want to use something like Terraform to manage their infrastructure since you can't know ahead of time the name of the security group/etc.

I think the best way to go about this is probably looking into making a change to the Magnum API to make the label r/w and then have a list of ports that are opened in that way.

**Comment by mnaser** [comment]
Another thing that we can do is loosen up inter-VM cluster traffic, by looking at few other examples:

- [AWS](https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html) seems to configure allowing all inbound traffic inside the security group (allowing all internal traffic) and all outbound traffic to the internet.  They seem to allow you to modify the security group but it would automatically recreate the allow all internal traffic, so things are not "locked down".
- [GKE](https://cloud.google.com/kubernetes-engine/docs/concepts/firewall-rules) seems to also do the same as allowing all inter-VM traffic as well.

With this, I think it would make sense to allow all in cluster traffic out of the box to improve usability:

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/3c742d2cd136ca2c64b1245a97230ae038eafe84/docs/book/src/clusteropenstack/configuration.md?plain=1#L483-L486
