### ISSUE TITLE
CA handling

### ISSUE THREAD

**Issue by jrosser** [vexxhost/magnum-cluster-api#204]
This might be a documentation or code issue or both.

We might see:

- A simple deployment (devstack?)
      1. No TLS
      2. Simple flat network
      3. One API endpoint(devstack?)

- A CI use case (openstack-ansible/kolla perhaps)
      1. API loadbalancer with internal/admin and external endpoints
      2. IP routes to either endpoints
      3. TLS certificates on internal and external endpoints created from a temporary CA

- A production use case
      1. API loadbalancer with internal/admin and external endpoints
      2. Routing (or not) at the deployers choice between the internal/external networks
      3. A cert on the external API endpoint (private company CA, LetsEncrypt, self-signed, Commercial CA....)
      4. A self-signed cert on the internal API endpoint managed by the deployment
 
We need to be able to tell:

- The k8s running cluster_api in the openstack control plane which endpoint to contact, and optionally supply a CA certificate to use
- The k8s deployed using magnum-cluster-api which endpoint to contact, and optionally supply a CA certiticate to use (may be different to the one suppled to the control plane)

It would be great to have some documentation (a diagram?) describing what talks to what, where the endpoints to use are configured and how the relevant CA certificates are passed.

The immediate bug reported here is that there is no mechanism in place in magnum-cluster-api to pass a CA certificate into the deployed nodes. This leads to an SSL failure in the deployed nodes in openstack-ansible CI as the self-signed cert on the external endpoint is not trusted.

Whilst supplying the same CA as used in the cluster_api control plane would work and fix the CI use case for openstack-ansible, this is actually a corner case as it is quite likely that different CA have been used to issue the internal and external endpoint certificates. Ideally it should be possible to explicitly define different CA to use for the control plane and the deployed nodes.

**Comment by okozachenko1203** [comment]
@jrosser I will divide your issue into 3 small issues
- [ ] bug: CA file is not passed to CloudConfigSecret maintained by this driver https://github.com/vexxhost/magnum-cluster-api/issues/207
- [ ] fr/qa: use different CAs for magnum components
- [ ] doc: Add configuration options in doc https://github.com/vexxhost/magnum-cluster-api/issues/205

Lets discuss `fr/qa: use different CAs for magnum components` here.

from your use cases, I think this is not only related to CA but also related to endpoint type. I can say you want to use different Openstack auth config per clients.

We have 3 openstack api clients in magnum scope.
- Magnum service components(Api and Conductor, mcapi driver is included as a part or Conductor): They consume other openstack service apis(nova, neutron, etc.) and we define client auth config per openstack service type via `[neutron_client]`, `[nova_client]`, `[glance_client]`, etc. in `magnum.conf`. In those option groups, we can set `endpoint_type`, `insecure` and `ca_file`. 
- coe clusters(ccm, csi, etc.): Current `[drivers]` group in `magnum.conf` is for this client type. But it only includes CA related options and doesn't allow configuring `endpoint_type`. Rather let them(coe clusters) use public endpoint because they are tenant resources. So public endpoint is more reasonable rather than internal one from the security perspective.
- cluster-api: It consumes openstack apis but there is no dedicated client auth config for this. This is our driver-specific component so maybe we can define `[cluster_api_client]` option group and define `endpoint_type`, `insecure` and `ca_file` at least. Btw, now we don't do like this and just let CAPI to use public endpoint and `[drivers]` group options for CA config.

To wrap up, with the current mcapi driver,
- coe cluster nodes only consume public endpoints and you can define custom CA in `[drivers]/openstack_ca_file`
- magnum-cluster-api(mcapi) driver consumes openstack endpoints configured in magnum.conf as a magnum service component. Magnum allows to use different client config per openstack service like `[neturon_client]`, `[nova_client]`, etc.
- cluster-api only consumes public endpoints and you can define custom CA in `[drivers]/openstack_ca_file` (once this issue is fixed #207)

**Comment by okozachenko1203** [comment]
@mnaser
https://github.com/vexxhost/magnum-cluster-api/blob/13c3e0f5735dbdac13cd9b1f197e28ea0f249bf0/magnum_cluster_api/driver.py#L46-L52
Now we use public endpoint for both coe clusters(ccm, csi) and capi(openstackMachineTemplate, openstackClusterTemplate).
I think we don't need to allow coe clusters to consume internal endpoint. But for capi, it is considerable so maybe we create a new option group `[capi_client]` and create a different secret for capi which uses options in `[capi_client]` group?
What is your opinion?

**Comment by okozachenko1203** [comment]
https://github.com/vexxhost/magnum-cluster-api/issues/207
https://github.com/vexxhost/magnum-cluster-api/issues/205
https://github.com/vexxhost/magnum-cluster-api/issues/210
