### ISSUE TITLE
Make use of servergroups for cluster nodes

### ISSUE THREAD

**Issue by robincron** [vexxhost/magnum-cluster-api#375]
Heat based Magnum clusters automatically assign soft-anti-affinity server groups to cluster nodes, which is neat.
I see that there is a PR in CAPO with the goal to also do this -> https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1912

I think it would be a good effort to get this into mcapi, as to try and spread out control plane nodes or give the user to control this behaviour for worker nodes, when the previous PR is merged

**Comment by fnpanic** [comment]
This approach makes absolutly sense. The users expect the control plane to be highly avaiable even in one AZ because they have 3 nodes. So from my point of view the control plane server group should be not soft-anti-affinity but anti-affinity by default. WIth the CAPO patch it should be possible for the user to control a per nodegroup affinity setting with a default to  soft-anti-affinity.
