### ISSUE TITLE
Add Manila CSI

### ISSUE THREAD

**Issue by mnaser** [vexxhost/magnum-cluster-api#79]
We should detect what services are running in the cloud (such as Manila or Cinder) and then install the appropriate CSI.

We already deploy Cinder but all the time, instead, we should deploy it if we detect the Cinder service, and the same goes for Manila, that way we finally have `ReadWriteMany` volumes! :)

**Comment by mnaser** [comment]
I think the direction we'll probably go in this is that the user will have to create a `StorageClass` on their own afterwards pointing at the correct `shareNetwork`.

**Comment by okozachenko1203** [comment]
WIP: https://github.com/vexxhost/magnum-cluster-api/pull/80

**Comment by okozachenko1203** [comment]
> I think the direction we'll probably go in this is that the user will have to create a `StorageClass` on their own afterwards pointing at the correct `shareNetwork`.

@mnaser  yeah, surely.
because a share_network is a tenant-defined object and customers can choose on-fly, we cannot detect it programmatically.

How about this? I think we can have one more label `manila_shared_network_id`, if it is not specified, we will skip creating the default SC(StorageClass) for manila and if it is specified, we will create a default SC using that.
Even if users didn't specify it as coe cluster label, they can create SC themselves after the cluster creation

**Comment by okozachenko1203** [comment]
one more thing is `shareNetworkID` is only mandatory when `driver_handles_share_servers=true`. if users didn't enable it, we don't need to require share_network_id to create the RWM storageclass. 
So we have to detect/know `driver_handles_share_servers` value and decide the required params for SC creation.
Or we can just leave this kind of configuration for SC creation to the user instead of such a complex detection>
