### ISSUE TITLE
Magnum/CAPI provisioned Kubernetes cluster name length

### ISSUE THREAD

**Issue by runlevel-six** [vexxhost/magnum-cluster-api#96]
Is there a way to customize the name used by the Magnum API (using the CAPI driver) built into Atmosphere? We are running into issues where operators are adding labels to artifacts that exceed the 63 character limit built into Kubernetes, and a big chunk of the label is the cluster name in these cases. It would be nice if we can define a name (such as `prod-k8s-00` or something like that) that tells the user exactly what it is used for and doesn't include the additional Magnum (and/or CAPI/CAPO) syntax.

```bash
trivy k8s cluster --compliance k8s-cis --report summary 
2023-03-25T16:59:00.124-0400	FATAL	get k8s artifacts error: running node-collector job: Job.batch "node-collector-foo-test-4admbibsdj-default-worker-infra-rb4bh-f2h5t" is invalid: spec.template.labels: Invalid value: "node-collector-foo-test-4admbibsdj-default-worker-infra-rb4bh-f2h5t": must be no more than 63 characters
```

**Comment by mnaser** [comment]
@runlevel-six: I think this is an interesting problem, right now, we are generating cluster names in the following way:

https://github.com/vexxhost/magnum-cluster-api/blob/main/magnum_cluster_api/utils.py#L45-L58

We're using cluster name + 10 characters.  Since we're creating all of them inside the `magnum-system` namespace, we can't really have clusters with the name only, unless we start creating clusters in different namespaces but that starts to get a little bit more complicated and becomes a much bigger change.

I think what we can do is probably drop that down to 5 characters, that might help a little bit?

**Comment by runlevel-six** [comment]
@mnaser I think that will definitely help, and we can work to shorten our cluster names as well. Any chance we can also shorten the node names since that is part of the overall length for some application applied labels?

I ask because in the example above, it looks like the name is `foo-test-4admbibsdj-default-worker-infra-rb4bh-f2h5t` which looks to be a mix of cluster name + 10 characters + worker name  + 2 five character strings. In that example the cluster name was solely `foo-test` and all the rest is appended by Magnum.

**Comment by mnaser** [comment]
Unfortunately the server name component actually comes from the Cluster API so we have to look for something there

**Comment by runlevel-six** [comment]
Ok, thanks
